name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "actix_middleware_macro"
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --all
  doctest:
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install stable --profile minimal
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "actix_middleware_macro"
      - name: Run doctests
        run: cargo test --doc
