name: Rust

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "ci" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: rustup toolchain install stable --profile minimal
    
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "later"

    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all
    - name: Run doctests
      run: cargo test --doc
